name: Optimize Android App Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  optimize_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      # Install Terser for code optimization
      - name: Install Terser
        run: npm install -g terser@latest
      
      # Recode and redesign Android app source code files using Terser and DeepAI image generation
      - name: Recode and Redesign Files
        run: |
          # Recode and optimize code files using Terser
          find . -type f \( -name '*.java' -o -name '*.xml' \) -exec timeout 180s terser --compress --mangle --output {} {} \;
          
          # Find and redesign images using DeepAI image generation tool while keeping them in place
          find . -type f \( -name '*.jpg' -o -name '*.png' \) -exec timeout 180s deepai redesign --input {} --output {} \;
        continue-on-error: true

      # Zip redesigned files
      - name: Zip Redesigned Files
        run: zip -r redesigned_files.zip .
      
      # Upload the zip file as an artifact
      - name: Upload Zip File
        uses: actions/upload-artifact@v2
        with:
          name: redesigned-files
          path: redesigned_files.zip
